// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $airport_airport_ from "./routes/airport/[airport].tsx";
import * as $airport_index from "./routes/airport/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $jokes_jokes_ from "./routes/jokes/[jokes].tsx";
import * as $jokes_index from "./routes/jokes/index.tsx";
import * as $recipe_recipe_ from "./routes/recipe/[recipe].tsx";
import * as $recipe_index from "./routes/recipe/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/airport/[airport].tsx": $airport_airport_,
    "./routes/airport/index.tsx": $airport_index,
    "./routes/index.tsx": $index,
    "./routes/jokes/[jokes].tsx": $jokes_jokes_,
    "./routes/jokes/index.tsx": $jokes_index,
    "./routes/recipe/[recipe].tsx": $recipe_recipe_,
    "./routes/recipe/index.tsx": $recipe_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
